### ISSUE TITLE
Build the RoI&RoDAlign libraries.

### ISSUE THREAD

**Issue by cherryolg** [bo-zhang-cs/GAIC-Pytorch#1]
When I perform"sudo bash make_all.sh",
`E=rod_align_api -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/zm/wd/GAIC/untils/rod_align/build/temp.linux-x86_64-3.6/src/rod_align_kernel.o `
'Compiling rod_align kernels by nvcc...
In file included from rod_align_kernel.cu:2:0:
rod_align_kernel.h:4:21: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
                     ^
compilation terminated.'
Can you help me with this problem? Looking forward to your reply!

**Comment by bo-zhang-cs** [comment]
For compilation issues, please follow instructions on building RoI&RoDAlign in https://github.com/lld533/Grid-Anchor-based-Image-Cropping-Pytorch.

**Comment by cherryolg** [comment]
Hello, I did compile it according to the above

“

1.nvcc -c -o roi_align_kernel.cu.o roi_align_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_60

2.export CUDA_HOME=/home/zm/wd/GAIC/untils/roi_align/make.sh &amp;&amp; python3 setup.py install

“

Both of these have been modified.

But still report the following




“ errorFAILED:/home/zm/wd/GAIC/untils/roi_align/build/temp.linux-x86_64-3.6/src/roi_align_kernel.o

FAILED:/home/zm/wd/GAIC/untils/roi_align/build/temp.linux-x86_64-3.6/src/roi_align_cuda.o

Traceback (most recent call last):

&nbsp; File "setup.py", line 65, in <module&gt;

&nbsp;&nbsp;&nbsp; 'build_ext': BuildExtension

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup

&nbsp;&nbsp;&nbsp; return distutils.core.setup(**attrs)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/core.py", line 148, in setup

&nbsp;&nbsp;&nbsp; dist.run_commands()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 955, in run_commands

&nbsp;&nbsp;&nbsp; self.run_command(cmd)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command

&nbsp;&nbsp;&nbsp; cmd_obj.run()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run

&nbsp;&nbsp;&nbsp; self.do_egg_install()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install

&nbsp;&nbsp;&nbsp; self.run_command('bdist_egg')

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command

&nbsp;&nbsp;&nbsp; self.distribution.run_command(command)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command

&nbsp;&nbsp;&nbsp; cmd_obj.run()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run

&nbsp;&nbsp;&nbsp; cmd = self.call_command('install_lib', warn_dir=0)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command

&nbsp;&nbsp;&nbsp; self.run_command(cmdname)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command

&nbsp;&nbsp;&nbsp; self.distribution.run_command(command)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command

&nbsp;&nbsp;&nbsp; cmd_obj.run()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run

&nbsp;&nbsp;&nbsp; self.build()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/install_lib.py", line 107, in build

&nbsp;&nbsp;&nbsp; self.run_command('build_ext')

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command

&nbsp;&nbsp;&nbsp; self.distribution.run_command(command)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command

&nbsp;&nbsp;&nbsp; cmd_obj.run()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run

&nbsp;&nbsp;&nbsp; _build_ext.run(self)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 339, in run

&nbsp;&nbsp;&nbsp; self.build_extensions()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions

&nbsp;&nbsp;&nbsp; build_ext.build_extensions(self)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions

&nbsp;&nbsp;&nbsp; self._build_extensions_serial()

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial

&nbsp;&nbsp;&nbsp; self.build_extension(ext)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension

&nbsp;&nbsp;&nbsp; _build_ext.build_extension(self, ext)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension

&nbsp;&nbsp;&nbsp; depends=ext.depends)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile

&nbsp;&nbsp;&nbsp; with_cuda=with_cuda)

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects

&nbsp;&nbsp;&nbsp; error_prefix='Error compiling objects for extension')

&nbsp; File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build

&nbsp;&nbsp;&nbsp; raise RuntimeError(message)

RuntimeError: Error compiling objects for extension

Compiling rod_align kernels by nvcc...

In file included from rod_align_kernel.cu:2:0:

rod_align_kernel.h:4:21: fatal error: THC/THC.h: No such file or directory

&nbsp;#include <THC/THC.h&gt;

 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^

”


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bo-zhang-cs/GAIC-Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bo-zhang-cs/GAIC-Pytorch] Build the RoI&amp;RoDAlign libraries. (Issue #1)





 
For compilation issues, please follow instructions on building RoI&amp;RoDAlign in https://github.com/lld533/Grid-Anchor-based-Image-Cropping-Pytorch.

**Comment by cherryolg** [comment]
Hello, I did compile it according to the above
`nvcc -c -o roi_align_kernel.cu.o roi_align_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_60
export CUDA_HOME=/home/zm/wd/GAIC/untils/roi_align/make.sh && python3 setup.py install
`
Both of these have been modified.
But still report the following 
`errorFAILED:/home/zm/wd/GAIC/untils/roi_align/build/temp.linux-x86_64-3.6/src/roi_align_kernel.o
FAILED:/home/zm/wd/GAIC/untils/roi_align/build/temp.linux-x86_64-3.6/src/roi_align_cuda.o
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    'build_ext': BuildExtension
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/Anaconda3/envs/torch16/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
Compiling rod_align kernels by nvcc...
In file included from rod_align_kernel.cu:2:0:
rod_align_kernel.h:4:21: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
                     ^
`
Could you help me?

**Comment by cherryolg** [comment]
I also want to ask, is this compilation related to the GCC version? My GCC is 4.8.5
 
Python：3.6
 
Torch：1.6





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bo-zhang-cs/GAIC-Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bo-zhang-cs/GAIC-Pytorch] Build the RoI&amp;RoDAlign libraries. (Issue #1)





 
For compilation issues, please follow instructions on building RoI&amp;RoDAlign in https://github.com/lld533/Grid-Anchor-based-Image-Cropping-Pytorch.
