### ISSUE TITLE
Multi-scale features concatenation

### ISSUE THREAD

**Issue by KostyaAtarik** [bo-zhang-cs/GAIC-Pytorch#2]
The paper says that multi-scale features are just concatenated but in your [code](https://github.com/bo-zhang-cs/GAIC-Pytorch/blob/877d6a325943c0a098324dc6d4a975ff4097c3f6/networks/GAIC_model.py#L180) it's 
`cat_feat = torch.cat((f3,f4,0.5*f5),1)`.
Why is `f5` feature divided in half prior the concatenation here? Were the shared pretrained models trained with this multiplication?

**Comment by bo-zhang-cs** [comment]
Yes, I implemented this following the [official code](https://github.com/HuiZeng/Grid-Anchor-based-Image-Cropping-Pytorch/blob/master/croppingModel.py#L270). The shared models were also trained with this multiplication.

**Comment by KostyaAtarik** [comment]
Thanks for the quick response!
Are you aware of any reason behind this multiplication, or should I better ask in the official repository?

**Comment by bo-zhang-cs** [comment]
Sorry, I'm not clear about this. I'm afraid you have to ask the original author.
